string_slice=input("Please Enter the string to process: ")
print(string_slice[2])
print(string_slice[1:-1])
print(string_slice[0:5])
print(string_slice[0:-2])
print(string_slice[::2])
print(string_slice[1::2])
print(string_slice[len(string_slice)::-1])
print(string_slice[-2::-2])
print("length of string is",len(string_slice))
